[providers]
  [providers.docker]
    constraints = "Label(`traefik.constraint-label`, `traefic-public`)"
    exposedByDefault = false
    swarmMode = true
    network = "traefik_public"

[api]
  #insecure = true
  #dashboard = true

[certificatesResolvers.jakedin-public.acme]
  email = "ghjnut@gmail.com"
  storage = "/etc/letsencrypt/acme.json"
  # for TLS-ALPN-01 ACME challenge
  [certificatesResolvers.jakedin-pubic.acme.tlsChallenge]

[entryPoints]
  [entryPoints.plex]
    # SSL+insecure
    address = ":32400"
    #debug = true
