version: '3.7'

services:
  agent:
    # TODO pin, point to registry
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == hansel.jaked.in]
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 5
    configs:
      - source: pingwave.hcl
        target: /pingwave.hcl
    networks:
      - graphite
    command: --config-file /pingwave.hcl --statsd-host graphite_server

networks:
  graphite:
    external: true
    name: graphite_default

configs:
  pingwave.hcl:
    name: pingwave-${SETTINGS_TIMESTAMP:?SETTINGS_TIMESTAMP not set}.hcl
    file: config/pingwave.hcl
