version: '3.7'

services:
  server:
    image: prom/prometheus:v2.13.1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == hansel.jaked.in]
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 0
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_default"
        - "traefik.http.routers.prometheus.entrypoints=webinternal"
        - "traefik.http.routers.prometheus.rule=Host(`prometheus.jaked.in.local`)"
        - "traefik.http.routers.prometheus.service=prometheus"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    configs:
      - source: config
        target: /etc/prometheus/prometheus.yml
    networks:
      - exporter
      - server
      - traefik_default
    restart: always
    volumes:
      - data:/prometheus

  cadvisor_exporter:
    image: google/cadvisor:v0.33.0
    deploy:
      endpoint_mode: dnsrr
      mode: global
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 0
    networks:
      - exporter
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node_exporter:
    image: prom/node-exporter:v0.18.1
    #image: quay.io/prometheus/node-exporter
    # map hostname:
    # node_uname_info{domainname="(none)",machine="x86_64",
    # nodename="derek.jaked.in",release="5.0.0-36-generic",sysname="Linux",
    # version="#39-Ubuntu SMP Tue Nov 12 09:46:06 UTC 2019"} 1

    hostname: "{{.Node.Hostname}}"
    deploy:
      endpoint_mode: dnsrr
      mode: global
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 0
    pid: "host"
    networks:
      - exporter
    volumes:
      - "/:/host:ro,rslave"
    command: --path.rootfs=/host

networks:
  exporter:
    driver: overlay
    attachable: true
  server:
    driver: overlay
    attachable: true
  traefik_default:
    external: true

# TODO persist?
volumes:
  data:

configs:
  config:
    external: true
    name: prometheus-0.0.8
