version: '3.7'

services:
  server:
    image: registry:2.7.1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == hansel.jaked.in]
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 0
    networks:
      - registry
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: ingress
    volumes:
      - data:/var/lib/registry

networks:
  registry:
    driver: overlay
    attachable: true

volumes:
  data:
