version: '3.8'

services:
  server:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    # TODO: volume or config?
    volumes:
      - type: bind
        source: /var/lib/homeassistant
        target: /config
    networks:
      - traefik-private
    environment:
      TZ: ${TZ}
    # TODO:https://github.com/allfro/device-mapping-manager/blob/master/docker-compose.yml
    #devices:
    #  - "/dev/ttyACM0:/dev/ttyACM0"
    deploy:
      mode: replicated
      replicas: 1
      #placement:
      #  constraints: [ node.hostname == hansel.jaked.in ]
      placement:
        constraints:
          - node.labels.devices.ttyACM0==true
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-private
        - traefik.docker.network=traefik-private

        - traefik.http.routers.homeassistant-secure.entrypoints=websecure
        - traefik.http.routers.homeassistant-secure.rule=Host(`${DOMAIN:?DOMAIN not set}`)
        - traefik.http.routers.homeassistant-secure.tls=true

        - traefik.http.services.homeassistant.loadbalancer.server.port=${LB_PORT:?LB_PORT not set}

networks:
  traefik-private:
    name: traefik-private
    external: true
