version: '3.7'

services:
  server:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    volumes:
      - type: bind
        source: /var/lib/homeassistant
        target: /config
    networks:
      - traefik-private
    environment:
      TZ: ${TZ}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == hansel.jaked.in]
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-private
        - traefik.docker.network=traefik-private

        - traefik.http.routers.homeassistant.entrypoints=websecure
        - traefik.http.routers.homeassistant.rule=Host(`${DOMAIN:?DOMAIN not set}`)
        - traefik.http.routers.homeassistant.tls=true

        - traefik.http.services.homeassistant.loadbalancer.server.port=${LB_PORT:?LB_PORT not set}

networks:
  traefik-private:
    name: traefik-private
    external: true
