version: '3.7'

services:
  deluged:
    image: 127.0.0.1:5000/ghjnut/deluge:1.3.12
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == hansel.jaked.in]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_default"
        - "traefik.http.routers.deluged.entrypoints=deluged"
        - "traefik.http.routers.deluged.rule=Host(`deluged.jaked.in.local`)"
        - "traefik.http.routers.deluged.service=deluged"
        # daemon
        - "traefik.http.services.deluged.loadbalancer.server.port=58846"
    networks:
      - deluge
      - traefik_default
    ports:
      # external connections
      - "58946:58946"
    volumes:
      # TODO move to /var/lib
      - type: bind
        source: /home/ghjnut/projects/docker/deluge/data
        target: /data
      # TODO move to /var/lib
      - type: bind
        source: /home/ghjnut/projects/docker/deluge/config
        target: /root/.config
    command: deluged --do-not-daemonize --loglevel=info

  web:
    image: 127.0.0.1:5000/ghjnut/deluge:1.3.12
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == hansel.jaked.in]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_default"
        - "traefik.http.routers.deluge.entrypoints=web"
        - "traefik.http.routers.deluge.rule=Host(`deluge.jaked.in.local`)"
        - "traefik.http.routers.deluge.service=deluge"
        - "traefik.http.services.deluge.loadbalancer.server.port=8112"
    networks:
      - deluge
      - traefik_default
    volumes:
      - type: bind
        source: /home/ghjnut/projects/docker/deluge/config
        target: /root/.config
    command: deluge-web --loglevel=info

# TODO make config and data into volumes

networks:
  deluge:
    driver: overlay
    attachable: true
  traefik_default:
    external: true
