version: '3.7'

services:
  deluged:
    # TODO pipe through traefik (for some reason wasn't working)
    #image: registry.jaked.in.internal:5000/deluge:2.0.3
    image: 127.0.0.1:5000/deluge:2.0.3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == hansel.jaked.in]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_default"
        - "traefik.tcp.routers.deluged.entrypoints=deluged"
        - "traefik.tcp.routers.deluged.rule=Host(`deluged.jaked.in.local`)"
        - "traefik.tcp.routers.deluged.service=deluged"
        # daemon
        - "traefik.tcp.services.deluged.loadbalancer.server.port=58846"
    networks:
      - deluge
      - traefik_default
    # TODO pipe through traefik
    ports:
      - "58846:58846"
      # public torrents connections
      - "58946:58946"
    volumes:
      # TODO move to /var/lib
      - type: bind
        source: /home/ghjnut/projects/docker/deluge/data
        target: /root/data
        #read_only: true
      # TODO move to /var/lib
      - type: bind
        source: /home/ghjnut/projects/docker/deluge/config
        target: /root/.config
        #read_only: true
    command: deluged --do-not-daemonize --loglevel info

  web:
    # TODO pipe through traefik (for some reason wasn't working)
    #image: registry.jaked.in.internal:5000/deluge:2.0.3
    image: 127.0.0.1:5000/deluge:2.0.3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == hansel.jaked.in]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_default"
        - "traefik.http.routers.deluge.entrypoints=webinternal"
        - "traefik.http.routers.deluge.rule=Host(`deluge.jaked.in.local`)"
        - "traefik.http.routers.deluge.service=deluge"
        - "traefik.http.services.deluge.loadbalancer.server.port=8112"
    networks:
      - deluge
      - traefik_default
    volumes:
      #- type: bind
      #  source: /home/ghjnut/projects/docker/deluge/config/deluge
      #  target: /config
      #  read_only: true
      - type: bind
        source: /home/ghjnut/projects/docker/deluge/config
        target: /root/.config
        #read_only: true
    command: deluge-web --do-not-daemonize --loglevel info

# TODO make config and data into volumes

networks:
  deluge:
    driver: overlay
    attachable: true
  traefik_default:
    external: true
