version: "3.7"

services:
  traefik:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    deploy:
      placement:
        constraints:
          - "node.labels.traefik-public.traefik-public-certificates==true"
    ports:
      # for TLS-ALPN-01 ACME challenge (letsencrypt https)
      - target: 443
        published: 4443
        protocol: tcp
        mode: ingress
      - target: 32400
        published: 32400
        protocol: tcp
        # 'host' to allow better forwarding of source IPs to plex
        mode: host
    networks:
      - public
    volumes:
      - type: volume
        source: acme
        target: /etc/letsencrypt
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    configs:
      - source: traefik.toml
        target: /etc/traefik/traefik.toml
        #labels:
        #  - traefik.http.routers.traefik.rule=Host(`${DOMAIN?Variable not set}`) && PathPrefix(`/dashboard`))
        #  - traefik.http.routers.traefik.service=api@internal
        #  - traefik.http.routers.traefik.middlewares=auth
        #  - traefik.http.middlewares.auth.basicauth.users=
        #  # Dummy service for Swarm port detection. The port can be any valid integer value.
        #  - traefik.http.services.dummy-svc.loadbalancer.server.port=9999

volumes:
  acme:

configs:
  traefik.toml:
    name: traefik-public-${SETTINGS_TIMESTAMP}.toml
    file: config/traefik.toml

networks:
  public:
    name: traefik-public
    driver: overlay
    attachable: true
