version: '3.7'

services:
  server:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == hansel.jaked.in]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 1
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-private
        - traefik.docker.network=traefik-private
        - traefik.http.routers.grafana.entrypoints=web
        - traefik.http.routers.grafana.rule=Host(`${DOMAIN:?DOMAIN not set}`)
        - traefik.http.services.grafana.loadbalancer.server.port=${LB_PORT:?LB_PORT not set}
    networks:
      - prometheus
      - graphite
      - traefik-private
    volumes:
      - type: volume
        source: data
        target: /var/lib/grafana

networks:
  prometheus:
    external: true
    name: prometheus_server
  graphite:
    external: true
    name: graphite_default
  traefik-private:
    name: traefik-private
    external: true

volumes:
  data:
