registry:
  # Docker registry url
  url: https://registry.jaked.in/v2
  # Docker registry fqdn
  name: registry.jaked.in
  # To allow image delete, should be false
  readonly: false
  auth:
    # Disable authentication
    enabled: false
