version: '3.7'

services:
  server:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == hansel]
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 0
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.plex.loadbalancer.server.port=32400"
        - "traefik.http.routers.traefik.service=plex"
        - "traefik.http.routers.traefik.rule=Host(`plex.jaked.in.local`) || (Host(`plex.jaked.in`)"
        - "traefik.http.routers.traefik.entrypoints=plex"
    environment:
      TZ: ${TZ}
      PLEX_CLAIM: ${PLEX_CLAIM}
      ADVERTISE_IP: ${ADVERTISE_IP}
      ALLOWED_NETWORKS: ${ALLOWED_NETWORKS}
    volumes:
      - type: bind
        source: /var/lib/plex/config
        target: /config
      - type: bind
        source: /var/lib/plex/transcode
        target: /transcode
      - type: bind
        source: /home/ghjnut/src/github.com/ghjnut/docker-beets/data/clean
        target: /data/Music
        read_only: true
