version: '3.7'

services:
  server:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    deploy:
      placement:
        constraints: [node.hostname == hansel.jaked.in]
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 0
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.http.routers.plex.entrypoints=plex
        - traefik.http.routers.plex.rule=Host(`${DOMAIN:?DOMAIN not set}`)
        - traefik.http.routers.plex.tls=true
        - traefik.http.routers.plex.tls.certresolver=${TLS_RESOLVER:?TLS_RESOLVER not set}
        - traefik.http.routers.plex.service=plex
        - traefik.http.services.plex.loadbalancer.server.port=${LB_PORT:?LB_PORT not set}
    environment:
      TZ: ${TZ}
      PLEX_CLAIM: ${PLEX_CLAIM}
      ADVERTISE_IP: ${ADVERTISE_IP}
      ALLOWED_NETWORKS: ${ALLOWED_NETWORKS}
    networks:
      - traefik-public
    volumes:
      - type: bind
        source: /var/lib/plex/config
        target: /config
      - type: bind
        source: /var/lib/plex/transcode
        target: /transcode
      - type: bind
        source: /home/ghjnut/src/github.com/ghjnut/docker-beets/data/clean
        target: /data/Music
        read_only: true

networks:
  traefik-public:
    name: traefik-public
    external: true
