version: "3.7"

services:
  traefik:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    deploy:
      placement:
        constraints: [node.hostname == hansel.jaked.in]
      #labels:
      #  - traefik.enable=true
      #  - traefik.constraint-label=traefik-private
      #  - traefik.docker.network=traefik-private
      #  - traefik.http.routers.traefik-private.entrypoints=websecure
      #  - traefik.http.routers.traefik-private.rule=Host(`${DOMAIN:?DOMAIN not set}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      #  - traefik.http.routers.traefik-private.service=api@internal
      #  # Dummy service for Swarm port detection. The port can be any valid integer value.
      #  - traefik.http.services.dummy-svc.loadbalancer.server.port=${LB_PORT:?LB_PORT not set}
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
    networks:
      - private
    volumes:
      #- type: volume
      #  source: traefik-dynamic
      #  target: /etc/traefik/dynamic_conf
      - type: volume
        source: private-cert
        target: /certs
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    configs:
      - source: traefik.toml
        target: /etc/traefik/traefik.toml
      - source: traefik-dynamic.toml
        target: /etc/traefik/dynamic_conf/traefik.toml

volumes:
  #traefik-dynamic:
  private-cert:

configs:
  traefik.toml:
    name: traefik-private-${SETTINGS_TIMESTAMP:?SETTINGS_TIMESTAMP not set}.toml
    file: config/traefik.toml
  traefik-dynamic.toml:
    name: traefik-private-dynamic-${SETTINGS_TIMESTAMP:?SETTINGS_TIMESTAMP not set}.toml
    file: config/traefik-dynamic.toml

networks:
  private:
    name: traefik-private
    driver: overlay
    attachable: true
