version: '3.7'

services:
  server:
    image: portainer/portainer:1.24.1
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      # fallback port
      - "9000:9000"
    volumes:
      - type: bind
        source: /var/lib/portainer
        target: /data
    networks:
      - traefik_default
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == hansel.jaked.in]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_default"
        - "traefik.http.routers.portainer.entrypoints=webinternal"
        - "traefik.http.routers.portainer.rule=Host(`portainer.jaked.in.local`)"
        - "traefik.http.routers.portainer.service=portainer"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
  agent:
    image: portainer/agent:2.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  agent_network:
    driver: overlay
    attachable: true
  traefik_default:
    external: true
