version: '3.7'

services:
  server:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == hansel.jaked.in]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 1
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-private
        - traefik.docker.network=traefik-private

       # https
        - traefik.http.routers.graphite-secure.entrypoints=websecure
        - traefik.http.routers.graphite-secure.rule=Host(`${DOMAIN:?DOMAIN not set}`)
        - traefik.http.routers.graphite-secure.tls=true

        - traefik.http.services.graphite.loadbalancer.server.port=${LB_PORT:?LB_PORT not set}
    networks:
      - default
      - traefik-private
    volumes:
      - conf:/opt/graphite/conf
      - storage:/opt/graphite/storage
      - statsd_conf:/opt/statsd/config

volumes:
  conf:
  storage:
  statsd_conf:

# TODO name: graphite_ingress?
networks:
  default:
    driver: overlay
    attachable: true
  traefik-private:
    name: traefik-private
    external: true
