version: "3.7"

services:
  nvidia_exporter:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    deploy:
      restart_policy:
        condition: any
    networks:
      - exporter
    environment:
      LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
    devices:
      - "/dev/nvidiactl:/dev/nvidiactl"
      - "/dev/nvidia0:/dev/nvidia0"
    volumes:
      # TODO figure out a more robust way to mount the right lib
      - "/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.${VERSION}:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1"

networks:
  exporter:
    name: prometheus_exporter
    external: true
