version: '3.7'

services:
  exporter:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==derek.jaked.in
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 5
    networks:
      - exporter
    environment:
      LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
    devices:
      - "/dev/nvidiactl:/dev/nvidiactl"
      - "/dev/nvidia0:/dev/nvidia0"
    volumes:
      - "${PATH_ML_LIB}:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1"

networks:
  exporter:
    name: prometheus_exporter
    external: true
