version: "3"

services:
  nvidia_exporter:
    image: mindprince/nvidia_gpu_prometheus_exporter:0.1
    deploy:
      restart_policy: 
        condition: any
    networks:
      - exporter
    environment:
      LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
    devices:
      - "/dev/nvidiactl:/dev/nvidiactl"
      - "/dev/nvidia0:/dev/nvidia0"
    volumes:
      # TODO figure out a more robust way to mount the right lib
      - "/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.455.23.04:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1"

networks:
  exporter:
    external:
      name: prometheus_exporter
