[log]
  level = "INFO"
  #level = "DEBUG"

# for healthcheck
[ping]

# TODO figure out how to enable the GUI
[api]
  insecure = false
  dashboard = false

[providers]
  [providers.file]
    filename = "/etc/traefik/dynamic_conf/traefik.toml"

  [providers.docker]
    constraints = "Label(`traefik.constraint-label`, `traefik-private`)"
    exposedByDefault = false
    swarmMode = true
    network = "traefik-private"

[entryPoints]
  [entryPoints.web]
    address = ":80"
    # TODO enable when internal SSL setup
    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
          to = "websecure"
          scheme = "https"

  # SSL+insecure
  [entryPoints.websecure]
    address = ":443/tcp"
    #debug = true
    #[entryPoints.websecure.http.tls]
    #  [[entryPoints.websecure.http.tls.domains]]
    #    main = "internal.jaked.in"
    #    sans = ["*.internal.jaked.in"]

    # Source IP forwarding (doesn't work, use host networking)
    #[entryPoints.websecure.proxyProtocol]
    #  trustedIPs = ["0.0.0.0/0"]
    #[entryPoints.websecure.forwardedHeaders]
    #  trustedIPs = ["0.0.0.0/0"]

  #[entryPoints.deluged-client]
  #  address = ":58846/tcp"
  #[entryPoints.deluged-tcp]
  #  address = ":58946/tcp"
  #[entryPoints.deluged-udp]
  #  address = ":58946/udp"

# Source IP forwarding (doesn't work, use host networking)
#[http.middlewares]
#  [http.middlewares.whitelist.ipWhiteList]
#    sourceRange = ["0.0.0.0/0"]
