[log]
  level = "INFO"
  #level = "DEBUG"

[providers]
  [providers.file]
    filename = "/etc/traefik/dynamic_conf/traefik.toml"

  [providers.docker]
    constraints = "Label(`traefik.constraint-label`, `traefik-private`)"
    exposedByDefault = false
    swarmMode = true
    network = "traefik-private"

[api]
  insecure = false
  dashboard = false

[entryPoints]
  [entryPoints.web]
    address = ":80"
    # TODO enable when internal SSL setup
    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
          to = "websecure"
          scheme = "https"

  # SSL+insecure
  [entryPoints.websecure]
    address = ":443/tcp"
    #debug = true
    #[entryPoints.websecure.http.tls]
    #  [[entryPoints.websecure.http.tls.domains]]
    #    main = "internal.jaked.in"
    #    sans = ["*.internal.jaked.in"]

  #[entryPoints.deluged-client]
  #  address = ":58846/tcp"
  #[entryPoints.deluged-tcp]
  #  address = ":58946/tcp"
  #[entryPoints.deluged-udp]
  #  address = ":58946/udp"
