version: "3.7"

services:
  traefik:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    deploy:
      #replicas: ${TRAEFIK_REPLICAS:-3}
      placement:
        constraints: [node.labels.traefik-public.traefik-public-certificates == true]

    ports:
      # for TLS-ALPN-01 ACME challenge
      - target: 443
        published: 443
        protocol: tcp
      # plex
      - target: 32400
        published: 32400
        protocol: tcp
        mode: host
    networks:
      - public
    volumes:
      - type: volume
        source: acme
        target: /etc/letsencrypt
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    configs:
      - source: traefik.toml
        target: /etc/traefik/traefik.toml

volumes:
  acme:

configs:
  traefik.toml:
    name: traefik-${SETTINGS_TIMESTAMP}.toml
    file: config/traefik.toml

networks:
  public:
    driver: overlay
    attachable: true
