version: "3.7"

services:
  traefik:
    image: "traefik:v2.5.1"
    deploy:
      #replicas: ${TRAEFIK_REPLICAS:-3}
      placement:
        constraints: [node.hostname == hansel.jaked.in]
        preferences:
          - spread: node.id
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.entrypoints=webinternal"
        - "traefik.http.routers.traefik.rule=Host(`traefik.jaked.in.local`)"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.services.api@internal.loadbalancer.server.port=80"
    ports:
      #- "80:80"
      - target: 443
        published: 443
        protocol: tcp
      - "8081:8081"
      #- target: 8443
      #  published: 8443
      #  protocol: tcp
      - "5000:5000"
      # TODO fix deluged TCP
      #- "58846:58846"
      - "32400:32400"
    networks:
      - default
    volumes:
      - type: volume
        source: acme
        target: /etc/letsencrypt
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    configs:
      - source: traefik.toml
        target: /etc/traefik/traefik.toml

volumes:
  acme:

#configs:
#  traefik_config:
#    name: traefik-7.toml
#    #file: ./traefik.toml
#    external: true

configs:
  traefik.toml:
    name: traefik-${SETTINGS_TIMESTAMP}.toml
    file: config/traefik.toml

networks:
  default:
    driver: overlay
    attachable: true
