[providers]
  [providers.docker]

[api]
  #insecure = true
  dashboard = true

[certificatesResolvers]
  [certificatesResolvers.public]
    [certificatesResolvers.public.acme]
      # TODO
      #email = "foobar"
      #caServer = "foobar"
      #preferredChain = "foobar"
      storage = "/etc/letsencrypt/acme.json"
      #httpchallenge = "acme.json"
      [certificatesResolvers.public.acme.httpChallenge]
        # has to be 80 or 443
        # https://community.letsencrypt.org/t/support-for-ports-other-than-80-and-443/3419/71
        entryPoint = "web"

[entryPoints]
  # TODO should be in service?
  [entryPoints.webinternal]
    address = ":8081"
  # TODO should be in service?
  [entryPoints.web]
    # necessary for http challenge
    # has to be 80 or 443
    # https://community.letsencrypt.org/t/support-for-ports-other-than-80-and-443/3419/71
    # TODO should be 443?
    address = ":80"
  [entryPoints.registry]
    address = ":5000"
  [entryPoints.deluged]
    address = ":58946"
  [entryPoints.delugedclient]
    address = ":58846"
  # TODO should be in service?
  [entryPoints.plex]
    # SSL+insecure
    address = ":32400"
  #debug = true
