version: '3.7'

services:
  server:
    image: kylemanna/openvpn:latest
    #networks:
    #  - openvpn
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - type: volume
        source: data
        target: /etc/openvpn
    #volumes:
    #  - type: bind
    #    source: /var/lib/openvpn
    #    target: /etc/openvpn

volumes:
  data:

#networks:
#  openvpn:
