version: '3.7'

services:
  server:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    #networks:
    #  - openvpn
    ports:
      - target: 1194
        published: 1194
        protocol: udp
        mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - type: volume
        source: data
        target: /etc/openvpn
    #volumes:
    #  - type: bind
    #    source: /var/lib/openvpn
    #    target: /etc/openvpn

volumes:
  data:

#networks:
#  openvpn:
