version: '3.7'

services:
  pihole:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == meekus.jaked.in]
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 0
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-private
        - traefik.docker.network=traefik-private
        - traefik.http.routers.pihole.entrypoints=web
        - traefik.http.routers.pihole.rule=Host(`${DOMAIN:?DOMAIN not set}`)
        - traefik.http.routers.pihole.service=pihole
        - traefik.http.services.pihole.loadbalancer.server.port=${LB_PORT:?LB_PORT not set}
    environment:
      TZ: ${TZ}
    #cap_add:
    #  - NET_ADMIN
    ports:
    - target: 53
      published: 53
      protocol: tcp
      mode: host
    - target: 53
      published: 53
      protocol: udp
      mode: host
    # DHCP
    #- target: 67
    #  published: 67
    #  protocol: udp
    #  mode: host
    #configs:
    #  - source: config
    #    target: /etc/prometheus/prometheus.yml
    networks:
      - pihole
      - traefik-private
    dns:
      - 127.0.0.1
    volumes:
      - pihole:/etc/pihole/
      - dnsmasq:/etc/dnsmasq.d/

  prometheus_exporter:
    image: ekofr/pihole-exporter:v0.0.11
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == meekus.jaked.in]
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 0
    environment:
      TZ: ${TZ}
      PIHOLE_HOSTNAME: 'pihole'
      PIHOLE_API_TOKEN: ''
      INTERVAL: ${EXPORTER_INTERVAL:?EXPORTER_INTERVAL not set}
      PORT: ${EXPORTER_PORT:?EXPORTER_PORT not set}
    networks:
      - pihole
      - prometheus_exporter

networks:
  pihole:
    driver: overlay
  prometheus_exporter:
    external: true
  traefik-private:
    name: traefik-private
    external: true

# TODO persist?
volumes:
  pihole:
  dnsmasq:

#configs:
#  config:
#    external: true
#    name: prometheus
