version: '3.7'

services:
  pihole:
    image: pihole/pihole:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == meekus.jaked.in]
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 0
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_default"
        - "traefik.http.routers.pihole.entrypoints=webinternal"
        - "traefik.http.routers.pihole.rule=Host(`pihole.jaked.in.local`)"
        - "traefik.http.routers.pihole.service=pihole"
        - "traefik.http.services.pihole.loadbalancer.server.port=80"
    environment:
      TZ: 'America/Denver'
    #cap_add:
    #  - NET_ADMIN
    ports:
    - target: 53
      published: 53
      protocol: tcp
      mode: host
    - target: 53
      published: 53
      protocol: udp
      mode: host
      #- "53:53"
      #- "67:67/udp"
      #- "80:80/tcp"
      #- "443:443/tcp"
    #configs:
    #  - source: config
    #    target: /etc/prometheus/prometheus.yml
    networks:
      - pihole
      - traefik_default
    dns:
      - 127.0.0.1
    restart: unless-stopped
    volumes:
      - pihole:/etc/pihole/
      - dnsmasq:/etc/dnsmasq.d/

  prometheus_exporter:
    image: ekofr/pihole-exporter:0.0.9
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == meekus.jaked.in]
      restart_policy:
        condition: any
        delay: 0s
        max_attempts: 0
      #labels:
      #  - "traefik.enable=true"
      #  - "traefik.docker.network=traefik_default"
      #  - "traefik.http.routers.pihole.entrypoints=webinternal"
      #  - "traefik.http.routers.pihole.rule=Host(`pihole.jaked.in.local`)"
      #  - "traefik.http.routers.pihole.service=pihole"
      #  - "traefik.http.services.pihole.loadbalancer.server.port=80"
    environment:
      TZ: 'America/Denver'
      PIHOLE_HOSTNAME: 'pihole'
      PIHOLE_API_TOKEN: ''
      INTERVAL: '30s'
      PORT: 9617
    #cap_add:
    #  - NET_ADMIN
    #ports:
    #  - "53:53"
    #configs:
    #  - source: config
    #    target: /etc/prometheus/prometheus.yml
    networks:
      - pihole
      - prometheus_exporter

networks:
  pihole:
    driver: overlay
    #attachable: true
  #server:
  #  driver: overlay
  #  attachable: true
  prometheus_exporter:
    external: true
  traefik_default:
    external: true

# TODO persist?
volumes:
  pihole:
  dnsmasq:

#configs:
#  config:
#    external: true
#    name: prometheus
